#!/bin/bash
set -eu

echo "Waitng 10m for checks"
sleep 600
echo "Starting checks"
while [ true ]
do
  if [ -z "$(redis-cli -h $REDIS_HOST CLUSTER INFO | awk '/cluster_state:ok/')" ]; then
    echo "Execute job $JOB_NAME"
    redis-cli -h $REDIS_HOST CLUSTER RESET HARD
    oc get --export -o yaml -n $POD_NAMESPACE job/$JOB_NAME > job.yaml
    sed -i '/controller-uid/d' job.yaml
    oc delete -n $POD_NAMESPACE job/$JOB_NAME
    oc apply -f job.yaml
    sleep 30
  fi;
  sleep 5
done
